# Este arquivo de workflow foi mantido por compatibilidade, mas todo o conteúdo
# relacionado ao GitHub Pages foi removido conforme solicitado.
# 
# Data: 21/05/2025
#
# Este arquivo deve ser excluído em um próximo commit no repositório.

name: Arquivo Descontinuado

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notificar sobre workflow obsoleto
        run: |
          echo "Este workflow está obsoleto e deve ser removido diretamente do repositório GitHub"