name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Set permissions for the GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Create package.json if not exists
        run: |
          if [ ! -f "package.json" ]; then
            echo "package.json not found, creating a basic one"
            echo '{
              "name": "design-to-code-playbook",
              "version": "1.0.0",
              "scripts": {
                "build": "mkdir -p build && cp -r docs images *.md build/"
              },
              "dependencies": {}
            }' > package.json
          fi
      
      - name: Install dependencies
        run: npm install
      
      - name: Build site
        run: npm run build
      
      - name: Create simple index.html if needed
        run: |
          if [ ! -f "build/index.html" ]; then
            echo "Creating index.html file"
            mkdir -p build
            cat > build/index.html << 'EOL'
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Design to Code Playbook</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
  <style>
    :root {
      --primary-color: #3578e5;
      --secondary-color: #6c757d;
    }
    body { 
      font-family: system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
      line-height: 1.5;
      color: #1c1e21;
    }
    .hero {
      padding: 4rem 0;
      text-align: center;
      background: linear-gradient(180deg, #f5f6f7 0%, #ffffff 100%);
    }
    .hero-title {
      font-size: 3rem;
      font-weight: 700;
      margin-bottom: 1rem;
    }
    .hero-subtitle {
      font-size: 1.5rem;
      font-weight: 400;
      color: var(--secondary-color);
      margin-bottom: 2rem;
    }
    .features {
      padding: 4rem 0;
      background-color: #ffffff;
    }
    .feature-card {
      padding: 2rem;
      text-align: center;
      border-radius: 8px;
      box-shadow: 0 2px 12px rgba(0, 0, 0, 0.1);
      height: 100%;
    }
    .feature-title {
      font-size: 1.5rem;
      font-weight: 600;
      margin: 1rem 0;
    }
    .cta-button {
      display: inline-block;
      padding: 0.75rem 1.5rem;
      background-color: var(--primary-color);
      color: white;
      font-weight: 600;
      border-radius: 4px;
      text-decoration: none;
      transition: background-color 0.2s;
    }
    .cta-button:hover {
      background-color: #2c66c3;
      color: white;
    }
    .footer {
      padding: 2rem 0;
      background-color: #f5f6f7;
    }
    .footer-column h3 {
      font-size: 1.25rem;
      font-weight: 600;
      margin-bottom: 1rem;
    }
    .footer-link {
      display: block;
      color: var(--secondary-color);
      margin-bottom: 0.5rem;
      text-decoration: none;
    }
    .footer-link:hover {
      color: var(--primary-color);
    }
    .copyright {
      text-align: center;
      padding-top: 2rem;
      border-top: 1px solid #e4e6e8;
      margin-top: 2rem;
      color: var(--secondary-color);
    }
  </style>
</head>
<body>
  <div class="hero">
    <div class="container">
      <h1 class="hero-title">Design to Code Playbook</h1>
      <p class="hero-subtitle">Convert designs to code efficiently using AI tools</p>
      <a href="docs/" class="cta-button">Get Started</a>
    </div>
  </div>

  <div class="features">
    <div class="container">
      <div class="row">
        <div class="col-md-4 mb-4">
          <div class="feature-card">
            <h3 class="feature-title">Comprehensive Design-to-Code</h3>
            <p>Learn the complete workflow from Figma designs to functional code with step-by-step guides.</p>
          </div>
        </div>
        <div class="col-md-4 mb-4">
          <div class="feature-card">
            <h3 class="feature-title">AI-Powered Development</h3>
            <p>Leverage GitHub Copilot, Azure AI, and other tools to accelerate your development process.</p>
          </div>
        </div>
        <div class="col-md-4 mb-4">
          <div class="feature-card">
            <h3 class="feature-title">Hands-On Experience</h3>
            <p>Follow practical workshops and real-world examples to build your skills with modern frameworks.</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <footer class="footer">
    <div class="container">
      <div class="row">
        <div class="col-md-4 footer-column">
          <h3>Docs</h3>
          <a href="docs/introduction" class="footer-link">Introduction</a>
          <a href="docs/getting-started" class="footer-link">Getting Started</a>
        </div>
        <div class="col-md-4 footer-column">
          <h3>Community</h3>
          <a href="https://github.com/paulasilvatech/Design-to-Code-Playbook/discussions" class="footer-link">GitHub Discussions</a>
          <a href="https://discord.gg/design-to-code" class="footer-link">Discord</a>
        </div>
        <div class="col-md-4 footer-column">
          <h3>More</h3>
          <a href="https://github.com/paulasilvatech/Design-to-Code-Playbook" class="footer-link">GitHub</a>
          <a href="https://www.figma.com/community/file/design-to-code" class="footer-link">Figma Community</a>
        </div>
      </div>
      <div class="copyright">
        Copyright © 2025 Design to Code Playbook
      </div>
    </div>
  </footer>

  <!-- Add Bootstrap JS for any interactive components -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
EOL
          fi
      
      - name: List build directory contents
        run: ls -la build/
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4